# librerias----
library(apputils)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(bslib)
library(readxl)
library(tidyverse)
library(dplyr)
library(dashboardthemes)
library(DT)
library(scales)
library(plotly)
library(lubridate)
library(RColorBrewer)
library(RODBC)
library(Microsoft365R)
library(rhandsontable)
library(scales)
library(stringi)
library(scales)

load("data/datos.Rdata")

## Valores ------
fecha_min <- as.Date(floor_date(max(tabla_informe$Fecha_Factura), unit = "year"))
fecha_max <- as.Date(floor_date(max(tabla_informe$Fecha_Factura), unit = "month") - days(1))